/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameCoin } from "./GameCoin";
export type { OffGridCore } from "./OffGridCore";
export type { RankRegistry } from "./RankRegistry";
