/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameCoin } from "./GameCoin";
export type { LapLogicCore } from "./LapLogicCore";
export type { RankRegistry } from "./RankRegistry";
