/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OffGridCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createRace"
      | "distributeReward"
      | "distributeRewards"
      | "enterRace"
      | "entryFeeCoins"
      | "gameCoin"
      | "getParticipants"
      | "getRacePool"
      | "hasEntered"
      | "hasUserEntered"
      | "owner"
      | "platformFeePercent"
      | "raceParticipants"
      | "racePools"
      | "renounceOwnership"
      | "setEntryFee"
      | "setPlatformFee"
      | "transferOwnership"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntryRecorded"
      | "OwnershipTransferred"
      | "RaceCreated"
      | "RaceSettled"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createRace",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRewards",
    values: [BytesLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "enterRace",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entryFeeCoins",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gameCoin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRacePool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEntered",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserEntered",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raceParticipants",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "racePools",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEntryFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createRace", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enterRace", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entryFeeCoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameCoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRacePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasEntered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasUserEntered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raceParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "racePools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace EntryRecordedEvent {
  export type InputTuple = [
    raceId: BytesLike,
    user: AddressLike,
    feeCoins: BigNumberish
  ];
  export type OutputTuple = [raceId: string, user: string, feeCoins: bigint];
  export interface OutputObject {
    raceId: string;
    user: string;
    feeCoins: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaceCreatedEvent {
  export type InputTuple = [raceId: BytesLike];
  export type OutputTuple = [raceId: string];
  export interface OutputObject {
    raceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaceSettledEvent {
  export type InputTuple = [raceId: BytesLike, totalPool: BigNumberish];
  export type OutputTuple = [raceId: string, totalPool: bigint];
  export interface OutputObject {
    raceId: string;
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    raceId: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [raceId: string, user: string, amount: bigint];
  export interface OutputObject {
    raceId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OffGridCore extends BaseContract {
  connect(runner?: ContractRunner | null): OffGridCore;
  waitForDeployment(): Promise<this>;

  interface: OffGridCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createRace: TypedContractMethod<[raceId: BytesLike], [void], "nonpayable">;

  distributeReward: TypedContractMethod<
    [user: AddressLike, amountCoins: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeRewards: TypedContractMethod<
    [raceId: BytesLike, winners: AddressLike[], shares: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  enterRace: TypedContractMethod<[raceId: BytesLike], [void], "nonpayable">;

  entryFeeCoins: TypedContractMethod<[], [bigint], "view">;

  gameCoin: TypedContractMethod<[], [string], "view">;

  getParticipants: TypedContractMethod<[raceId: BytesLike], [string[]], "view">;

  getRacePool: TypedContractMethod<
    [raceId: BytesLike],
    [
      [bigint, bigint, boolean] & {
        totalPool: bigint;
        entryCount: bigint;
        isSettled: boolean;
      }
    ],
    "view"
  >;

  hasEntered: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasUserEntered: TypedContractMethod<
    [raceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  raceParticipants: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  racePools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, boolean, boolean] & {
        totalPool: bigint;
        entryCount: bigint;
        isSettled: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEntryFee: TypedContractMethod<
    [_feeCoins: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_percent: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawPlatformFees: TypedContractMethod<
    [amountCoins: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createRace"
  ): TypedContractMethod<[raceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [user: AddressLike, amountCoins: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeRewards"
  ): TypedContractMethod<
    [raceId: BytesLike, winners: AddressLike[], shares: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterRace"
  ): TypedContractMethod<[raceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entryFeeCoins"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gameCoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[raceId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRacePool"
  ): TypedContractMethod<
    [raceId: BytesLike],
    [
      [bigint, bigint, boolean] & {
        totalPool: bigint;
        entryCount: bigint;
        isSettled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEntered"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserEntered"
  ): TypedContractMethod<
    [raceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raceParticipants"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "racePools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, boolean, boolean] & {
        totalPool: bigint;
        entryCount: bigint;
        isSettled: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEntryFee"
  ): TypedContractMethod<[_feeCoins: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_percent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[amountCoins: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EntryRecorded"
  ): TypedContractEvent<
    EntryRecordedEvent.InputTuple,
    EntryRecordedEvent.OutputTuple,
    EntryRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RaceCreated"
  ): TypedContractEvent<
    RaceCreatedEvent.InputTuple,
    RaceCreatedEvent.OutputTuple,
    RaceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RaceSettled"
  ): TypedContractEvent<
    RaceSettledEvent.InputTuple,
    RaceSettledEvent.OutputTuple,
    RaceSettledEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "EntryRecorded(bytes32,address,uint256)": TypedContractEvent<
      EntryRecordedEvent.InputTuple,
      EntryRecordedEvent.OutputTuple,
      EntryRecordedEvent.OutputObject
    >;
    EntryRecorded: TypedContractEvent<
      EntryRecordedEvent.InputTuple,
      EntryRecordedEvent.OutputTuple,
      EntryRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RaceCreated(bytes32)": TypedContractEvent<
      RaceCreatedEvent.InputTuple,
      RaceCreatedEvent.OutputTuple,
      RaceCreatedEvent.OutputObject
    >;
    RaceCreated: TypedContractEvent<
      RaceCreatedEvent.InputTuple,
      RaceCreatedEvent.OutputTuple,
      RaceCreatedEvent.OutputObject
    >;

    "RaceSettled(bytes32,uint256)": TypedContractEvent<
      RaceSettledEvent.InputTuple,
      RaceSettledEvent.OutputTuple,
      RaceSettledEvent.OutputObject
    >;
    RaceSettled: TypedContractEvent<
      RaceSettledEvent.InputTuple,
      RaceSettledEvent.OutputTuple,
      RaceSettledEvent.OutputObject
    >;

    "RewardDistributed(bytes32,address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
