/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RankRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "backendWriter"
      | "batchSetRanks"
      | "getCurrentRank"
      | "getRank"
      | "owner"
      | "ranks"
      | "renounceOwnership"
      | "seasonLeaders"
      | "setBackendWriter"
      | "setRank"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RankUpdated"
      | "SeasonReset"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "backendWriter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetRanks",
    values: [
      AddressLike[],
      BigNumberish[],
      string[],
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRank",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ranks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonLeaders",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackendWriter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRank",
    values: [AddressLike, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "backendWriter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetRanks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ranks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonLeaders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBackendWriter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RankUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    season: BigNumberish,
    rank: BigNumberish,
    rankName: string,
    points: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    season: bigint,
    rank: bigint,
    rankName: string,
    points: bigint
  ];
  export interface OutputObject {
    user: string;
    season: bigint;
    rank: bigint;
    rankName: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeasonResetEvent {
  export type InputTuple = [season: BigNumberish];
  export type OutputTuple = [season: bigint];
  export interface OutputObject {
    season: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RankRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RankRegistry;
  waitForDeployment(): Promise<this>;

  interface: RankRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backendWriter: TypedContractMethod<[], [string], "view">;

  batchSetRanks: TypedContractMethod<
    [
      users: AddressLike[],
      rankValues: BigNumberish[],
      rankNames: string[],
      pointsArr: BigNumberish[],
      season: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getCurrentRank: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, string, bigint] & {
        rank: bigint;
        rankName: string;
        totalPoints: bigint;
      }
    ],
    "view"
  >;

  getRank: TypedContractMethod<
    [user: AddressLike, season: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        rank: bigint;
        rankName: string;
        totalPoints: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ranks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint] & {
        rank: bigint;
        rankName: string;
        totalPoints: bigint;
        season: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seasonLeaders: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  setBackendWriter: TypedContractMethod<
    [_writer: AddressLike],
    [void],
    "nonpayable"
  >;

  setRank: TypedContractMethod<
    [
      user: AddressLike,
      rank: BigNumberish,
      rankName: string,
      totalPoints: BigNumberish,
      season: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backendWriter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchSetRanks"
  ): TypedContractMethod<
    [
      users: AddressLike[],
      rankValues: BigNumberish[],
      rankNames: string[],
      pointsArr: BigNumberish[],
      season: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentRank"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, string, bigint] & {
        rank: bigint;
        rankName: string;
        totalPoints: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRank"
  ): TypedContractMethod<
    [user: AddressLike, season: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        rank: bigint;
        rankName: string;
        totalPoints: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ranks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint] & {
        rank: bigint;
        rankName: string;
        totalPoints: bigint;
        season: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasonLeaders"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setBackendWriter"
  ): TypedContractMethod<[_writer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRank"
  ): TypedContractMethod<
    [
      user: AddressLike,
      rank: BigNumberish,
      rankName: string,
      totalPoints: BigNumberish,
      season: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RankUpdated"
  ): TypedContractEvent<
    RankUpdatedEvent.InputTuple,
    RankUpdatedEvent.OutputTuple,
    RankUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SeasonReset"
  ): TypedContractEvent<
    SeasonResetEvent.InputTuple,
    SeasonResetEvent.OutputTuple,
    SeasonResetEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RankUpdated(address,uint256,uint256,string,uint256)": TypedContractEvent<
      RankUpdatedEvent.InputTuple,
      RankUpdatedEvent.OutputTuple,
      RankUpdatedEvent.OutputObject
    >;
    RankUpdated: TypedContractEvent<
      RankUpdatedEvent.InputTuple,
      RankUpdatedEvent.OutputTuple,
      RankUpdatedEvent.OutputObject
    >;

    "SeasonReset(uint256)": TypedContractEvent<
      SeasonResetEvent.InputTuple,
      SeasonResetEvent.OutputTuple,
      SeasonResetEvent.OutputObject
    >;
    SeasonReset: TypedContractEvent<
      SeasonResetEvent.InputTuple,
      SeasonResetEvent.OutputTuple,
      SeasonResetEvent.OutputObject
    >;
  };
}
